version: "3.8"

services:
  php-jikken-nginx:
    image: nginx:latest
    container_name: php-jikken-nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php-jikken-php
    networks:
      - php-jikken-network

  php-jikken-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-jikken-php
    volumes:
      - ./src:/var/www/html
    networks:
      - php-jikken-network

  php-jikken-phpmyadmin:
    image: phpmyadmin:latest
    container_name: php-jikken-phpmyadmin
    ports:
      - "8002:80"
    environment:
      PMA_HOST: php-jikken-mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - php-jikken-mysql
    networks:
      - php-jikken-network

  php-jikken-mysql:
    image: mysql:latest
    container_name: php-jikken-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php-jikken-network

volumes:
  mysql_data:

networks:
  php-jikken-network: