version: '3.8'

services:
  php:
    image: php:8.1-fpm
    container_name: prewiki-php
    volumes:
      - ./prewiki:/var/www/html
    networks:
      - prewiki-network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: prewiki-nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./prewiki:/var/www/html
    depends_on:
      - php
    networks:
      - prewiki-network

  mysql:
    image: mysql:8.0
    container_name: prewiki-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prewiki
      MYSQL_USER: prewiki
      MYSQL_PASSWORD: prewiki
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prewiki-network

volumes:
  mysql_data:

networks:
  prewiki-network:


#a